<!DOCTYPE html>
<html>
<head>
    <title>Hall Booking Application Form</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
            text-transform: uppercase;
        }
        .header h2 {
            font-size: 14px;
            margin: 5px 0 0 0;
            font-weight: normal;
        }
        .title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 20px;
            text-decoration: underline;
        }
        .content-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .content-table th, .content-table td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }
        .content-table th {
            background-color: #f0f0f0;
            width: 30%;
        }
        .signature-section {
            margin-top: 50px;
        }
        .signature-box {
            float: left;
            width: 45%;
        }
        .signature-box.right {
            float: right;
            text-align: right;
        }
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            border-top: 1px solid #ccc;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>District Secretariat - Vavuniya</h1>
        <h2>Resource Management System</h2>
    </div>

    <div class="title">Conference Hall Booking Application Form</div>

    <table class="content-table">
        <tr>
            <th>Application No</th>
            <td>{{ $booking->booking_id }}</td>
        </tr>
        <tr>
            <th>Applicant Name</th>
            <td>{{ $booking->applicant_name }}</td>
        </tr>
        <tr>
            <th>Applicant Type</th>
            <td>{{ $booking->applicant_type }}</td>
        </tr>
        <tr>
            <th>Hall Type</th>
            <td>{{ $booking->requested_hall_type ?? $booking->hall->hall_type }}</td>
        </tr>
        <tr>
            <th>Programme / Event</th>
            <td>{{ $booking->programme }}</td>
        </tr>
        <tr>
            <th>Event Date</th>
            <td>{{ \Carbon\Carbon::parse($booking->event_date)->format('Y-m-d') }}</td>
        </tr>
        <tr>
            <th>Event Time</th>
            <td>{{ \Carbon\Carbon::parse($booking->event_time)->format('h:i A') }}</td>
        </tr>
        <tr>
            <th>Duration</th>
            <td>{{ $booking->event_duration }} Hours</td>
        </tr>
        <tr>
            <th>Number of Participants</th>
            <td>{{ $booking->participants }}</td>
        </tr>
        <tr>
            <th>Paid Status</th>
            <td>{{ $booking->paid_status }}</td>
        </tr>
        <tr>
            <th>Emergency Booking</th>
            <td>{{ $booking->is_emergency_booking ? 'Yes' : 'No' }}</td>
        </tr>
        <tr>
            <th>Requested By (NIC)</th>
            <td>{{ $booking->filled_by_nic }}</td>
        </tr>
        <tr>
            <th>Contact Number</th>
            <td>{{ $booking->filled_by_phone }}</td>
        </tr>
    </table>

    <div class="signature-section clearfix">
        <div class="signature-box">
            <br><br><br>
            __________________________<br>
            Signature of Applicant<br>
            Date: {{ $date }}
        </div>
        
        <div class="signature-box right">
            <br><br><br>
            __________________________<br>
            Administrative Officer<br>
            (District Secretariat)
        </div>
    </div>

    <div class="footer">
        Generated by Resource Booking System - Vavuniya on {{ \Carbon\Carbon::now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
