<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Quarter Allocation Letter</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 14px;
            line-height: 1.6;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .title {
            font-weight: bold;
            text-decoration: underline;
            margin-bottom: 20px;
            font-size: 16px;
        }

        .content {
            margin-bottom: 20px;
        }

        .footer {
            margin-top: 50px;
        }

        .signature {
            margin-top: 50px;
        }

        ul {
            list-style-type: disc;
            margin-left: 20px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>District Secretariat, Vavuniya</h2>
        <p>Resource Booking System</p>
    </div>

    <div class="content">
        <p class="title">ALLOCATION OF GOVERNMENT QUARTERS</p>

        <p><strong>Date:</strong> {{ $date }}</p>

        <p>Dear {{ $application->officer_name }},</p>

        <p>We are pleased to inform you that you have been allocated the following government quarter:</p>

        <p>
            <strong>Quarter No:</strong> {{ $quarter->quarter_id ?? 'N/A' }}<br>
            <strong>Location:</strong> {{ $quarter->location ?? 'N/A' }}<br>
            <strong>Type:</strong> {{ $quarter->quarter_type ?? 'N/A' }}<br>
            <strong>Duration:</strong> From {{ \Carbon\Carbon::parse($allocation->allocation_date)->format('Y-m-d') }}
            To {{ \Carbon\Carbon::parse($allocation->vacate_date)->format('Y-m-d') }}
        </p>

        <p><strong>Conditions of Allocation:</strong></p>
        <ul>
            <li>Alcohol and drugs are strictly prohibited within the quarter premises.</li>
            <li>Residents are responsible for the safety of their own belongings.</li>
            <li>Any damages to the property must be reported immediately and may be liable for compensation.</li>
            <li>The allocated officer must sign an agreement with the Government Agent acknowledging all conditions.
            </li>
            <li>Rent will be deducted from your monthly salary as per government regulations.</li>
            <li>This allocation is subject to the rules and regulations of the Public Administration Circulars.</li>
        </ul>

        <p>Please report to the District Secretariat to sign the agreement and collect the keys.</p>
    </div>

    <div class="footer">
        <div class="signature">
            <p>..................................................<br>
                Government Agent / District Secretary,<br>
                District Secretariat, Vavuniya.</p>
        </div>

        <p style="font-size: 10px; margin-top: 30px;">
            Generated by Resource Booking System on {{ \Carbon\Carbon::now()->format('Y-m-d H:i:s') }}
        </p>
    </div>
</body>

</html>